---
default_external_services:
  gcs_bucket: kubernetes-azure/
  gcs_pull_prefix: kubernetes-azure/pr-logs/pull
  prow_url: "40.67.190.149"
  spyglass: true
external_services:
  istio:
    gcs_pull_prefix: istio-prow/pull
    prow_url: prow.istio.io
default_org: ritazh
default_repo: kubernetes
jobs:
  kubernetes-azure/pr-logs/directory/:
  - pull-kubernetes-e2e-aks-engine-azure
recursive_artifacts: false
