---
default_external_services:
  gcs_bucket: kubernetes-azure/
  gcs_pull_prefix: kubernetes-azure/pr-logs/pull
  prow_url: "13.77.181.53"
  spyglass: true
external_services:
  istio:
    gcs_pull_prefix: istio-prow/pull
    prow_url: prow.istio.io
default_org: ritazh
default_repo: kubernetes
jobs:
  kubernetes-azure/pr-logs/directory/:
  - pull-kubernetes-e2e-aks-engine-azure
  kubernetes-azure/pr-logs/:
  - ci-kubernetes-e2e-aks-engine-azure-master-windows
  kubernetes-azure/logs/:
  - ci-kubernetes-e2e-aks-engine-azure-master-windows
recursive_artifacts: false
